tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "surface-dim": "#dbdad9",
                "tertiary": "#4f0200",
                "on-secondary": "#ffffff",
                "on-error": "#ffffff",
                "tertiary-fixed": "#ffdad4",
                "error-container": "#ffdad6",
                "surface-container-low": "#f5f3f3",
                "tertiary-container": "#780400",
                "surface-container-lowest": "#ffffff",
                "on-error-container": "#93000a",
                "surface-bright": "#fbf9f8",
                "on-secondary-container": "#fffbff",
                "on-tertiary": "#ffffff",
                "secondary-container": "#6462ec",
                "on-primary-fixed": "#02006e",
                "surface-container": "#efeded",
                "surface-variant": "#e4e2e2",
                "on-background": "var(--on-background)",
                "inverse-on-surface": "#f2f0f0",
                "surface-container-highest": "#e4e2e2",
                "primary-fixed-dim": "#bfc2ff",
                "on-primary": "#ffffff",
                "inverse-primary": "#bfc2ff",
                "on-surface": "var(--on-surface)",
                "surface-tint": "#4249de",
                "inverse-surface": "#303031",
                "outline": "#767686",
                "surface": "var(--surface)",
                "on-primary-fixed-variant": "#262bc7",
                "tertiary-fixed-dim": "#ffb4a7",
                "primary-fixed": "#e0e0ff",
                "primary": "#030086",
                "on-tertiary-fixed-variant": "#8c170a",
                "on-primary-container": "#949aff",
                "outline-variant": "#c6c5d8",
                "surface-container-high": "#e9e8e7",
                "error": "#ba1a1a",
                "on-secondary-fixed-variant": "#332dbc",
                "secondary": "#4a47d2",
                "primary-container": "#1111bb",
                "on-tertiary-fixed": "#400100",
                "on-tertiary-container": "#ff7b66",
                "background": "var(--background)",
                "secondary-fixed": "#e2dfff",
                "secondary-fixed-dim": "#c2c1ff",
                "on-surface-variant": "var(--on-surface-variant)",
                "on-secondary-fixed": "#0b006b"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "fontFamily": {
                "headline": ["Manrope"],
                "body": ["Inter"],
                "label": ["Inter"]
            }
        },
    },
};
